name: wakelock_example
description: Demonstrates how to use the wakelock plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  wakelock:
    path: ../

flutter:
  uses-material-design: true
