name: wakelock
description: Wakelock is a Flutter plugin that allows you to easily toggle the Android and iOS screen wakelock on or off in order to prevent the screen from automatically turning off.
version: 0.1.0
author: creativecreatorormaybenot <19204050+creativecreatorormaybenot@users.noreply.github.com>
homepage: https://github.com/creativecreatorormaybenot/wakelock

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: 1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: wakelock.wakelock
    pluginClass: WakelockPlugin