name: wakelock
description: This plugin allows you to keep Android and iOS devices awake, i.e. prevent the screen from sleeping by toggling the wakelock of the device on or off.
version: 0.1.3+1
homepage: https://github.com/creativecreatorormaybenot/wakelock

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  flutter:
    sdk: flutter

flutter:
  platforms:
    android:
      package: wakelock.wakelock
      pluginClass: WakelockPlugin
    ios:
      pluginClass: WakelockPlugin
